<?php

	// Set the currency codes, glyphs, and descriptions array:
		$currency_data['USD']['glyph']	= '$';
		$currency_data['USD']['desc']	= 'US dollar';
		$currency_data['CAD']['glyph']	= '$';
		$currency_data['CAD']['desc']	= 'Canadian dollar';
		$currency_data['AUD']['glyph']	= '$';
		$currency_data['AUD']['desc']	= 'Australian dollar';
		$currency_data['BBD']['glyph']	= '$';
		$currency_data['BBD']['desc']	= 'Barbados dollar';
		$currency_data['BMD']['glyph']	= '$';
		$currency_data['BMD']['desc']	= 'Bermudian dollar';
		$currency_data['BND']['glyph']	= '$';
		$currency_data['BND']['desc']	= 'Brunei dollar';
		$currency_data['BSD']['glyph']	= '$';
		$currency_data['BSD']['desc']	= 'Bahamian dollar';
		$currency_data['BZD']['glyph']	= '$';
		$currency_data['BZD']['desc']	= 'Belize dollar';
		$currency_data['FJD']['glyph']	= '$';
		$currency_data['FJD']['desc']	= 'Fiji dollar';
		$currency_data['GYD']['glyph']	= '$';
		$currency_data['GYD']['desc']	= 'Guyana dollar';
		$currency_data['HKD']['glyph']	= '$';
		$currency_data['HKD']['desc']	= 'Hong Kong dollar';
		$currency_data['JMD']['glyph']	= '$';
		$currency_data['JMD']['desc']	= 'Jamaican dollar';
		$currency_data['KYD']['glyph']	= '$';
		$currency_data['KYD']['desc']	= 'Cayman Islands dollar';
		$currency_data['LRD']['glyph']	= '$';
		$currency_data['LRD']['desc']	= 'Liberian dollar';
		$currency_data['MGA']['glyph']	= '$';
		$currency_data['MGA']['desc']	= 'Malagasy ariary';
		$currency_data['NAD']['glyph']	= '$';
		$currency_data['NAD']['desc']	= 'Namibian dollar';
		$currency_data['NZD']['glyph']	= '$';
		$currency_data['NZD']['desc']	= 'New Zealand dollar';
		$currency_data['SBD']['glyph']	= '$';
		$currency_data['SBD']['desc']	= 'Solomon Islands dollar';
		$currency_data['SGD']['glyph']	= '$';
		$currency_data['SGD']['desc']	= 'Singapore dollar';
		$currency_data['SRD']['glyph']	= '$';
		$currency_data['SRD']['desc']	= 'Surinam dollar';
		$currency_data['TTD']['glyph']	= '$';
		$currency_data['TTD']['desc']	= 'Trinidad and Tobago dollar';
		$currency_data['TWD']['glyph']	= '$';
		$currency_data['TWD']['desc']	= 'New Taiwan dollar';
		$currency_data['TTD']['glyph']	= '$';
		$currency_data['TTD']['desc']	= 'Trinidad and Tobago dollar';
		$currency_data['TWD']['glyph']	= '$';
		$currency_data['TWD']['desc']	= 'New Taiwan dollar';
		$currency_data['XCD']['glyph']	= '$';
		$currency_data['XCD']['desc']	= 'East Caribbean dollar';
		$currency_data['ZWD']['glyph']	= '$';
		$currency_data['ZWD']['desc']	= 'Zimbabwe dollar';
		$currency_data['EUR']['glyph']	= '&euro;';
		$currency_data['EUR']['desc']	= 'Euro';
		$currency_data['GBP']['glyph']	= '&pound;';
		$currency_data['GBP']['desc']	= 'Pound sterling';
		$currency_data['AFN']['glyph']	= '&#x60B;';
		$currency_data['AFN']['desc']	= 'Afghani';
		$currency_data['THB']['glyph']	= '&#xE3F;';
		$currency_data['THB']['desc']	= 'Baht';
		$currency_data['PAB']['glyph']	= 'B/.';
		$currency_data['PAB']['desc']	= 'Balboa';
		$currency_data['XOF']['glyph']	= 'Fr';
		$currency_data['XOF']['desc']	= 'CFA Franc BCEAO';
		$currency_data['XAF']['glyph']	= 'Fr';
		$currency_data['XAF']['desc']	= 'CFA franc BEAC';
		$currency_data['BOB']['glyph']	= 'Bs.';
		$currency_data['BOB']['desc']	= 'Boliviano';
		$currency_data['GHS']['glyph']	= '&#x20B5;';
		$currency_data['GHS']['desc']	= 'Cedi';
		$currency_data['CRC']['glyph']	= '&#x20A1;';
		$currency_data['CRC']['desc']	= 'Costa Rican colon';
		$currency_data['CDF']['glyph']	= 'Fr';
		$currency_data['CDF']['desc']	= 'Franc Congolais';
		$currency_data['GMD']['glyph']	= 'D';
		$currency_data['GMD']['desc']	= 'Dalasi';
		$currency_data['MKD']['glyph']	= '&#x434;&#x435;&#x43D;';
		$currency_data['MKD']['desc']	= 'Denar';
		$currency_data['DZD']['glyph']	= '&#x62F;.&#x62C;';
		$currency_data['DZD']['desc']	= 'Algerian dinar';
		$currency_data['BHD']['glyph']	= '&#x628;.&#x62F;';
		$currency_data['BHD']['desc']	= 'Bahraini dinar';
		$currency_data['IQD']['glyph']	= '&#x639;.&#x62F;';
		$currency_data['IQD']['desc']	= 'Iraqi dinar';
		$currency_data['JOD']['glyph']	= '&#x62F;.&#x627;';
		$currency_data['JOD']['desc']	= 'Jordanian dinar';
		$currency_data['KWD']['glyph']	= '&#x62F;.&#x643;';
		$currency_data['KWD']['desc']	= 'Kuwaiti dinar';
		$currency_data['LYD']['glyph']	= '&#x644;.&#x62F;';
		$currency_data['LYD']['desc']	= 'Libyan dinar';
		$currency_data['RSD']['glyph']	= '&#x434;&#x438;&#x43D;.';
		$currency_data['RSD']['desc']	= 'Serbian dinar';
		$currency_data['TND']['glyph']	= '&#x62F;.&#x62A;';
		$currency_data['TND']['desc']	= 'Tunisian dinar';
		$currency_data['AED']['glyph']	= '&#x62F;.&#x645;.';
		$currency_data['AED']['desc']	= 'United Arab Emirates dirham';
		$currency_data['MAD']['glyph']	= '&#x62F;.&#x625;';
		$currency_data['MAD']['desc']	= 'Moroccan dirham';
		$currency_data['STD']['glyph']	= 'Db';
		$currency_data['STD']['desc']	= 'Dobra';
		$currency_data['AMD']['glyph']	= '&#x564;&#x580;.';
		$currency_data['AMD']['desc']	= 'Armenian dram';
		$currency_data['CVE']['glyph']	= 'Esc';
		$currency_data['CVE']['desc']	= 'Cape Verde escudo';
		$currency_data['HUF']['glyph']	= 'Ft';
		$currency_data['HUF']['desc']	= 'Forint';
		$currency_data['BIF']['glyph']	= 'Fr';
		$currency_data['BIF']['desc']	= 'Burundian franc';
		$currency_data['CHF']['glyph']	= 'CHF';
		$currency_data['CHF']['desc']	= 'Swiss franc';
		$currency_data['DJF']['glyph']	= 'Fr';
		$currency_data['DJF']['desc']	= 'Djibouti franc';
		$currency_data['GNF']['glyph']	= 'Fr';
		$currency_data['GNF']['desc']	= 'Guinea franc';
		$currency_data['KMF']['glyph']	= 'Fr';
		$currency_data['KMF']['desc']	= 'Comoro franc';
		$currency_data['RWF']['glyph']	= 'Fr';
		$currency_data['RWF']['desc']	= 'Rwanda franc';
		$currency_data['XPF']['glyph']	= 'Fr';
		$currency_data['XPF']['desc']	= 'CFP franc';
		$currency_data['HTG']['glyph']	= 'G';
		$currency_data['HTG']['desc']	= 'Haiti gourde';
		$currency_data['PYG']['glyph']	= '&#x20B2;';
		$currency_data['PYG']['desc']	= 'Guarani';
		$currency_data['ANG']['glyph']	= '&fnof;';
		$currency_data['ANG']['desc']	= 'Netherlands Antillian guilder';
		$currency_data['AWG']['glyph']	= '&fnof;';
		$currency_data['AWG']['desc']	= 'Aruban guilder';
		$currency_data['UAH']['glyph']	= '&#x20B4;';
		$currency_data['UAH']['desc']	= 'Hryvnia';
		$currency_data['PGK']['glyph']	= 'K';
		$currency_data['PGK']['desc']	= 'Kina';
		$currency_data['LAK']['glyph']	= '&#x20AD;';
		$currency_data['LAK']['desc']	= 'Kip';
		$currency_data['CZK']['glyph']	= 'K&#x10D;';
		$currency_data['CZK']['desc']	= 'Czech koruna';
		$currency_data['SKK']['glyph']	= 'Sk';
		$currency_data['SKK']['desc']	= 'Slovak koruna';
		$currency_data['ISK']['glyph']	= 'kr';
		$currency_data['ISK']['desc']	= 'Iceland krona';
		$currency_data['SEK']['glyph']	= 'kr';
		$currency_data['SEK']['desc']	= 'Swedish krona';
		$currency_data['DKK']['glyph']	= 'kr';
		$currency_data['DKK']['desc']	= 'Danish krone';
		$currency_data['NOK']['glyph']	= 'kr';
		$currency_data['NOK']['desc']	= 'Norwegian krone';
		$currency_data['HRK']['glyph']	= 'kn';
		$currency_data['HRK']['desc']	= 'Croatian kuna';
		$currency_data['MWK']['glyph']	= 'MK';
		$currency_data['MWK']['desc']	= 'Kwacha';
		$currency_data['ZMK']['glyph']	= 'ZK';
		$currency_data['ZMK']['desc']	= 'Kwacha';
		$currency_data['AOA']['glyph']	= 'Kz';
		$currency_data['AOA']['desc']	= 'Kwanza';
		$currency_data['MMK']['glyph']	= 'K';
		$currency_data['MMK']['desc']	= 'Kyat';
		$currency_data['GEL']['glyph']	= '&#x10DA;';
		$currency_data['GEL']['desc']	= 'Lari';
		$currency_data['LVL']['glyph']	= 'Ls';
		$currency_data['LVL']['desc']	= 'Latvian lats';
		$currency_data['ALL']['glyph']	= 'L';
		$currency_data['ALL']['desc']	= 'Lek';
		$currency_data['HNL']['glyph']	= 'L';
		$currency_data['HNL']['desc']	= 'Lempira';
		$currency_data['SLL']['glyph']	= 'Le';
		$currency_data['SLL']['desc']	= 'Leone';
		$currency_data['MDL']['glyph']	= 'L';
		$currency_data['MDL']['desc']	= 'Moldovan leu';
		$currency_data['RON']['glyph']	= 'L';
		$currency_data['RON']['desc']	= 'Romanian new leu';
		$currency_data['BGN']['glyph']	= '&#x43B;&#x432;';
		$currency_data['BGN']['desc']	= 'Bulgarian lev';
		$currency_data['SZL']['glyph']	= 'L';
		$currency_data['SZL']['desc']	= 'Lilangeni';
		$currency_data['TRY']['glyph']	= '&#x20A4;';
		$currency_data['TRY']['desc']	= 'New Turkish lira';
		$currency_data['LTL']['glyph']	= 'Lt';
		$currency_data['LTL']['desc']	= 'Lithuanian litas';
		$currency_data['LSL']['glyph']	= 'L';
		$currency_data['LSL']['desc']	= 'Loti';
		$currency_data['AZN']['glyph']	= 'm';
		$currency_data['AZN']['desc']	= 'Azerbaijanian manat';
		$currency_data['TMM']['glyph']	= 'm';
		$currency_data['TMM']['desc']	= 'Manat';
		$currency_data['BAM']['glyph']	= '&#x41A;&#x41C;';
		$currency_data['BAM']['desc']	= 'Convertible marks';
		$currency_data['MZN']['glyph']	= 'MTn';
		$currency_data['MZN']['desc']	= 'Metical';
		$currency_data['NGN']['glyph']	= '&#x20A6;';
		$currency_data['NGN']['desc']	= 'Naira';
		$currency_data['ERN']['glyph']	= 'Nfk';
		$currency_data['ERN']['desc']	= 'Nakfa';
		$currency_data['BTN']['glyph']	= '&#x20AB;';
		$currency_data['BTN']['desc']	= 'Ngultrum';
		$currency_data['OMR']['glyph']	= '&#x631;.&#x639;.';
		$currency_data['OMR']['desc']	= 'Rial Omani';
		$currency_data['NIO']['glyph']	= 'C$';
		$currency_data['NIO']['desc']	= 'Cordoba oro';
		$currency_data['MRO']['glyph']	= 'UM';
		$currency_data['MRO']['desc']	= 'Ouguiya';
		$currency_data['MOP']['glyph']	= 'P';
		$currency_data['MOP']['desc']	= 'Pataca';
		$currency_data['ARS']['glyph']	= '$';
		$currency_data['ARS']['desc']	= 'Argentine peso';
		$currency_data['CLP']['glyph']	= '$';
		$currency_data['CLP']['desc']	= 'Chilean peso';
		$currency_data['COP']['glyph']	= '$';
		$currency_data['COP']['desc']	= 'Colombian peso';
		$currency_data['CUP']['glyph']	= '$';
		$currency_data['CUP']['desc']	= 'Cuban peso';
		$currency_data['DOP']['glyph']	= '$';
		$currency_data['DOP']['desc']	= 'Dominican peso';
		$currency_data['MXN']['glyph']	= '$';
		$currency_data['MXN']['desc']	= 'Mexican peso';
		$currency_data['PHP']['glyph']	= '&#x20B1;';
		$currency_data['PHP']['desc']	= 'Philippine peso';
		$currency_data['EGP']['glyph']	= '&#x62C;.&#x645;';
		$currency_data['EGP']['desc']	= 'Egyptian pound';
		$currency_data['LBP']['glyph']	= '&#x644;.&#x644;';
		$currency_data['LBP']['desc']	= 'Lebanese pound';
		$currency_data['SYP']['glyph']	= '&#x644;.&#x633;';
		$currency_data['SYP']['desc']	= 'Syrian pound';
		$currency_data['FKP']['glyph']	= '&pound;';
		$currency_data['FKP']['desc']	= 'Falkland Islands pound';
		$currency_data['GIP']['glyph']	= '&pound;';
		$currency_data['GIP']['desc']	= 'Gibraltar pound';
		$currency_data['SDG']['glyph']	= '&pound;';
		$currency_data['SDG']['desc']	= 'Sudanese pound';
		$currency_data['SHP']['glyph']	= '&pound;';
		$currency_data['SHP']['desc']	= 'Saint Helena pound';
		$currency_data['BWP']['glyph']	= 'P';
		$currency_data['BWP']['desc']	= 'Pula';
		$currency_data['GTQ']['glyph']	= 'Q';
		$currency_data['GTQ']['desc']	= 'Quetzal';
		$currency_data['ZAR']['glyph']	= 'R';
		$currency_data['ZAR']['desc']	= 'South African rand';
		$currency_data['BRL']['glyph']	= 'R$';
		$currency_data['BRL']['desc']	= 'Real';
		$currency_data['CNY']['glyph']	= '&yen;';
		$currency_data['CNY']['desc']	= 'Renminbi';
		$currency_data['IRR']['glyph']	= '&#xFDFC;';
		$currency_data['IRR']['desc']	= 'Iranian rial';
		$currency_data['QAR']['glyph']	= '&#x631;.&#x642;';
		$currency_data['QAR']['desc']	= 'Qatari rial';
		$currency_data['YER']['glyph']	= '&#xFDFC;';
		$currency_data['YER']['desc']	= 'Yemeni rial';
		$currency_data['KHR']['glyph']	= '&#x17DB;';
		$currency_data['KHR']['desc']	= 'Riel';
		$currency_data['MYR']['glyph']	= 'RM';
		$currency_data['MYR']['desc']	= 'Malaysian ringgit';
		$currency_data['SAR']['glyph']	= '&#x631;.&#x633;';
		$currency_data['SAR']['desc']	= 'Saudi riyal';
		$currency_data['BYR']['glyph']	= 'Br';
		$currency_data['BYR']['desc']	= 'Belarussian ruble';
		$currency_data['RUB']['glyph']	= '&#x440;.';
		$currency_data['RUB']['desc']	= 'Russian ruble';
		$currency_data['MVR']['glyph']	= '&#x783;.';
		$currency_data['MVR']['desc']	= 'Rufiyaa';
		$currency_data['INR']['glyph']	= '&#x20A8;';
		$currency_data['INR']['desc']	= 'Indian rupee';
		$currency_data['LKR']['glyph']	= '&#xBB0;&#xBC2;';
		$currency_data['LKR']['desc']	= 'Sri Lanka rupee';
		$currency_data['MUR']['glyph']	= '&#x20A8;';
		$currency_data['MUR']['desc']	= 'Mauritius rupee';
		$currency_data['NPR']['glyph']	= '&#x20A8;';
		$currency_data['NPR']['desc']	= 'Nepalese rupee';
		$currency_data['PKR']['glyph']	= 'Rs.';
		$currency_data['PKR']['desc']	= 'Pakistan rupee';
		$currency_data['SCR']['glyph']	= '&#x20A8;';
		$currency_data['SCR']['desc']	= 'Seychelles rupee';
		$currency_data['IDR']['glyph']	= 'Rp';
		$currency_data['IDR']['desc']	= 'Rupiah';
		$currency_data['ILS']['glyph']	= '&#x20AA;';
		$currency_data['ILS']['desc']	= 'New Israeli shekel';
		$currency_data['KES']['glyph']	= 'Sh';
		$currency_data['KES']['desc']	= 'Kenyan shilling';
		$currency_data['SOS']['glyph']	= 'Sh';
		$currency_data['SOS']['desc']	= 'Somali shilling';
		$currency_data['TZS']['glyph']	= 'Sh';
		$currency_data['TZS']['desc']	= 'Tanzanian shilling';
		$currency_data['UGX']['glyph']	= 'Sh';
		$currency_data['UGX']['desc']	= 'Uganda shilling';
		$currency_data['PEN']['glyph']	= 'S/.';
		$currency_data['PEN']['desc']	= 'Nuevo sol';
		$currency_data['TJS']['glyph']	= '&#x405;&#x41C;';
		$currency_data['TJS']['desc']	= 'Somoni';
		$currency_data['BDT']['glyph']	= '&#x9F3;';
		$currency_data['BDT']['desc']	= 'Bangladeshi taka';
		$currency_data['WST']['glyph']	= 'T';
		$currency_data['WST']['desc']	= 'Samoan tala';
		$currency_data['KZT']['glyph']	= '&#x3012;';
		$currency_data['KZT']['desc']	= 'Tenge';
		$currency_data['MNT']['glyph']	= '&#x20AE;';
		$currency_data['MNT']['desc']	= 'Tugrik';
		$currency_data['UYU']['glyph']	= '$';
		$currency_data['UYU']['desc']	= 'Peso Uruguayo';
		$currency_data['VUV']['glyph']	= 'Vt';
		$currency_data['VUV']['desc']	= 'Vatu';
		$currency_data['KPW']['glyph']	= '&#x20A9;';
		$currency_data['KPW']['desc']	= 'North Korean won';
		$currency_data['KRW']['glyph']	= '&#x20A9;';
		$currency_data['KRW']['desc']	= 'South Korean won';
		$currency_data['JPY']['glyph']	= '&yen;';
		$currency_data['JPY']['desc']	= 'Japanese yen';
		$currency_data['PLN']['glyph']	= 'z&#x142;';
		$currency_data['PLN']['desc']	= 'Zloty';
		$currency_data['TOP']['glyph']	= 'T$';
		$currency_data['TOP']['desc']	= 'Pa&#x27;anga';

		// Short Names / Currency Name Only:
		$currency_data['USD']['name']	= 'Dollar';  	// United States
		$currency_data['CAD']['name']	= 'Dollar';		// Canada
		$currency_data['AUD']['name']	= 'Dollar';		// Australia
		$currency_data['BBD']['name']	= 'Dollar'; 	// Barbados
		$currency_data['BMD']['name']	= 'Dollar';		// Bermudian
		$currency_data['BND']['name']	= 'Dollar';		// Brunei
		$currency_data['BSD']['name']	= 'Dollar';		// Bahamian
		$currency_data['BZD']['name']	= 'Dollar';		// Belize
		$currency_data['FJD']['name']	= 'Dollar';		// Fiji
		$currency_data['GYD']['name']	= 'Dollar';		// Guyana
		$currency_data['HKD']['name']	= 'Dollar';		// Hong Kong
		$currency_data['JMD']['name']	= 'Dollar';		// Jamaican
		$currency_data['KYD']['name']	= 'Dollar';		// Cayman Islands
		$currency_data['LRD']['name']	= 'Dollar';		// Liberian
		$currency_data['MGA']['name']	= 'Ariary';		// Malagasy
		$currency_data['NAD']['name']	= 'Dollar';		// Namibian
		$currency_data['NZD']['name']	= 'Dollar';		// New Zealand
		$currency_data['SBD']['name']	= 'Dollar';		// Solomon Islands
		$currency_data['SGD']['name']	= 'Dollar';		// Singapore
		$currency_data['SRD']['name']	= 'Dollar';		// Surinam
		$currency_data['TTD']['name']	= 'Dollar';		// Trinidad and Tobago
		$currency_data['TWD']['name']	= 'Dollar';		// New Taiwan
		$currency_data['XCD']['name']	= 'Dollar';		// East Caribbean
		$currency_data['ZWD']['name']	= 'Dollar';		// Zimbabwe
		$currency_data['EUR']['name']	= 'Euro';
		$currency_data['GBP']['name']	= 'Pound Sterling';
		$currency_data['AFN']['name']	= 'Afghani';
		$currency_data['THB']['name']	= 'Baht';
		$currency_data['PAB']['name']	= 'Balboa';
		$currency_data['XOF']['name']	= 'Franc';		// CFA Franc BCEAO
		$currency_data['XAF']['name']	= 'Franc';		// CFA franc BEAC
		$currency_data['BOB']['name']	= 'Boliviano';
		$currency_data['GHS']['name']	= 'Cedi';
		$currency_data['CRC']['name']	= 'Colon';		// Costa Rican
		$currency_data['CDF']['name']	= 'Franc';		// Congolais
		$currency_data['GMD']['name']	= 'Dalasi';
		$currency_data['MKD']['name']	= 'Denar';
		$currency_data['DZD']['name']	= 'Dinar';		// Algerian
		$currency_data['BHD']['name']	= 'Dinar';		// Bahraini
		$currency_data['IQD']['name']	= 'Dinar';		// Iraqi
		$currency_data['JOD']['name']	= 'Dinar';		// Jordanian
		$currency_data['KWD']['name']	= 'Dinar';		// Kuwaiti
		$currency_data['LYD']['name']	= 'Dinar';		// Libyan
		$currency_data['RSD']['name']	= 'Dinar';		// Serbian
		$currency_data['TND']['name']	= 'Dinar';		// Tunisian
		$currency_data['AED']['name']	= 'Dirham';		// United Arab Emirates
		$currency_data['MAD']['name']	= 'Dirham';		// Moroccan
		$currency_data['STD']['name']	= 'Dobra';
		$currency_data['AMD']['name']	= 'Dram';		// Armenian
		$currency_data['CVE']['name']	= 'Escudo';		// Cape Verde
		$currency_data['HUF']['name']	= 'Forint';
		$currency_data['BIF']['name']	= 'Franc';		// Burundian
		$currency_data['CHF']['name']	= 'CHF';		// Swiss
		$currency_data['DJF']['name']	= 'Franc';		// Djibouti
		$currency_data['GNF']['name']	= 'Franc';		// Guinea
		$currency_data['KMF']['name']	= 'Franc';		// Comoro
		$currency_data['RWF']['name']	= 'Franc';		// Rwanda
		$currency_data['XPF']['name']	= 'Franc';		// CFP
		$currency_data['HTG']['name']	= 'Gourde';		// Haiti
		$currency_data['PYG']['name']	= 'Guarani';
		$currency_data['ANG']['name']	= 'Guilder';	// Netherlands Antillian
		$currency_data['AWG']['name']	= 'Guilder';	// Aruban
		$currency_data['UAH']['name']	= 'Hryvnia';
		$currency_data['PGK']['name']	= 'Kina';
		$currency_data['LAK']['name']	= 'Kip';
		$currency_data['CZK']['name']	= 'Koruna';		// Czech
		$currency_data['SKK']['name']	= 'Koruna';		// Slovak
		$currency_data['ISK']['name']	= 'Krona';		// Iceland
		$currency_data['SEK']['name']	= 'Krona';		// Swedish
		$currency_data['DKK']['name']	= 'Krone';		// Danish
		$currency_data['NOK']['name']	= 'Krone';		// Norwegian
		$currency_data['HRK']['name']	= 'Kuna';		// Croatian
		$currency_data['MWK']['name']	= 'Kwacha';
		$currency_data['ZMK']['name']	= 'Kwacha';
		$currency_data['AOA']['name']	= 'Kwanza';
		$currency_data['MMK']['name']	= 'Kyat';
		$currency_data['GEL']['name']	= 'Lari';
		$currency_data['LVL']['name']	= 'Lats';		// Latvian
		$currency_data['ALL']['name']	= 'Lek';
		$currency_data['HNL']['name']	= 'Lempira';
		$currency_data['SLL']['name']	= 'Leone';
		$currency_data['MDL']['name']	= 'Leu';		// Moldovan
		$currency_data['RON']['name']	= 'New Leu';	// Romanian
		$currency_data['BGN']['name']	= 'Lev';		// Bulgarian
		$currency_data['SZL']['name']	= 'Lilangeni';
		$currency_data['TRY']['name']	= 'New Lira';	// Turkish
		$currency_data['LTL']['name']	= 'Litas';		// Lithuanian
		$currency_data['LSL']['name']	= 'Loti';
		$currency_data['AZN']['name']	= 'Manat';		// Azerbaijanian
		$currency_data['TMM']['name']	= 'Manat';
		$currency_data['BAM']['name']	= 'Convertible marks';
		$currency_data['MZN']['name']	= 'Metical';
		$currency_data['NGN']['name']	= 'Naira';
		$currency_data['ERN']['name']	= 'Nakfa';
		$currency_data['BTN']['name']	= 'Ngultrum';
		$currency_data['OMR']['name']	= 'Rial Omani';
		$currency_data['NIO']['name']	= 'Cordoba oro';
		$currency_data['MRO']['name']	= 'Ouguiya';
		$currency_data['MOP']['name']	= 'Pataca';
		$currency_data['ARS']['name']	= 'Peso';		// Argentine
		$currency_data['CLP']['name']	= 'Peso';		// Chilean
		$currency_data['COP']['name']	= 'Peso';		// Colombian
		$currency_data['CUP']['name']	= 'Peso';		// Cuban
		$currency_data['DOP']['name']	= 'Peso';		// Dominican
		$currency_data['MXN']['name']	= 'Peso';		// Mexican
		$currency_data['PHP']['name']	= 'Peso';		// Philippine
		$currency_data['EGP']['name']	= 'Pound';		// Egyptian
		$currency_data['LBP']['name']	= 'Pound';		// Lebanese
		$currency_data['SYP']['name']	= 'Pound';		// Syrian
		$currency_data['FKP']['name']	= 'Pound';		// Falkland Islands
		$currency_data['GIP']['name']	= 'Pound';		// Gibraltar
		$currency_data['SDG']['name']	= 'Pound';		// Sudanese
		$currency_data['SHP']['name']	= 'Pound';		// Saint Helena
		$currency_data['BWP']['name']	= 'Pula';
		$currency_data['GTQ']['name']	= 'Quetzal';
		$currency_data['ZAR']['name']	= 'Rand';		// South African
		$currency_data['BRL']['name']	= 'Real';		// Brazilian
		$currency_data['CNY']['name']	= 'Renminbi';
		$currency_data['IRR']['name']	= 'Rial';		// Iranian
		$currency_data['QAR']['name']	= 'Rial';		// Qatari
		$currency_data['YER']['name']	= 'Rial';		// Yemen
		$currency_data['KHR']['name']	= 'Riel';
		$currency_data['MYR']['name']	= 'Ringgit';	// Malaysian
		$currency_data['SAR']['name']	= 'Riyal';		// Saudi
		$currency_data['BYR']['name']	= 'Ruble';		// Belarussian
		$currency_data['RUB']['name']	= 'Ruble';		// Russian
		$currency_data['MVR']['name']	= 'Rufiyaa';
		$currency_data['INR']['name']	= 'Rupee';		// Indian
		$currency_data['LKR']['name']	= 'Rupee';		// Sri Lanka
		$currency_data['MUR']['name']	= 'Rupee';		// Mauritius
		$currency_data['NPR']['name']	= 'Rupee';		// Nepalese
		$currency_data['PKR']['name']	= 'Rupee';		// Pakistan
		$currency_data['SCR']['name']	= 'Rupee';		// Seychelles
		$currency_data['IDR']['name']	= 'Rupiah';
		$currency_data['ILS']['name']	= 'New Shekel';	// Israeli
		$currency_data['KES']['name']	= 'Shilling';	// Kenyan
		$currency_data['SOS']['name']	= 'Shilling';	// Somali
		$currency_data['TZS']['name']	= 'Shilling';	// Tanzanian
		$currency_data['UGX']['name']	= 'Shilling';	// Uganda
		$currency_data['PEN']['name']	= 'Nuevo Sol';
		$currency_data['TJS']['name']	= 'Somoni';
		$currency_data['BDT']['name']	= 'Taka';		// Bangladeshi
		$currency_data['WST']['name']	= 'Tala';		// Samoan
		$currency_data['KZT']['name']	= 'Tenge';
		$currency_data['MNT']['name']	= 'Tugrik';
		$currency_data['UYU']['name']	= 'Peso';		// Uruguay
		$currency_data['VUV']['name']	= 'Vatu';
		$currency_data['KPW']['name']	= 'Won';		// North Koren
		$currency_data['KRW']['name']	= 'Won';		// South Korean
		$currency_data['JPY']['name']	= 'Yen';		// Japanese
		$currency_data['PLN']['name']	= 'Zloty';
		$currency_data['TOP']['name']	= 'Pa&#x27;anga';

		$GLOBALS['currency_data'] = $currency_data;

?>
